[package]
name = "nemasvg"
version = "0.2.0"
edition = "2024"

[lib]
name = "nemasvg"
path = "src/lib.rs"

[[bin]]
name = "nemasvg"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
avt = "0.18"
base64 = "0.23"
clap = { version = "4.5", features = ["derive"] }
fontcull = { version = "2.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ttf-parser = "0.25"
ttf2woff2 = "0.13"
zstd = "0.14"
